name: "Hello World"
description: "Greet someone"
inputs:
  input-who-to-greet: # id of input
    description: "Who to greet"
    required: true    
  input-test-input-1:
    description: "test input 1"
    required: true
  input-test-input-2:
    description: "test input 2"
    required: true

runs:
  using: "composite"
  steps:
    - name: Do something
      run: echo "${{inputs.input-who-to-greet}} ${{inputs.input-test-input-1}} ${{inputs.input-test-input-2}}"
      shell: bash
      
    - name: Stuff
      run: |
        print_inputs () {
          local str="command "
          local inputs='${{ toJSON(inputs) }}'
          local keys=$(echo $inputs | jq -r ". | keys[]" )  
          for k in $keys; do
            # export variable $k as key in jq ctx
            local value=$(echo $inputs | jq --arg key $k -r '.[$key]')
            local key_without_prefix=${k#input-} 
            local key_in_caps=$(echo ${key_without_prefix^^} | tr '-' '_')       
             
            echo $key_in_caps=$value >> $GITHUB_ENV
            local str="$str --${key_in_caps}=$value"
          done
          echo $str
        }
        res=$(print_inputs)
        echo $res
        
      shell: bash
    - run: echo ${WHO_TO_GREET}
      shell: bash

  

