name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true    
  test-input-1:
    description: "test input 1"
    required: true
  test-input-2:
    description: "test input 2"
    required: true

runs:
  using: "composite"
  steps:
    - name: Do something
      run: echo "${{inputs.who-to-greet}} ${{inputs.test-input-1}} ${{inputs.test-input-2}}"
      shell: bash
    - run: |
        inputs=${{ toJSON(inputs)}}
        keys=$(echo $inputs | jq -r ". | keys[]" )
        echo $keys
      shell: bash
  
