name: "Hello World"
description: "Greet someone"
inputs:
  input-who-to-greet: # id of input
    description: "Who to greet"
    required: true    
  input-test-input-1:
    description: "test input 1"
    required: true
  input-test-input-2:
    description: "test input 2"
    required: true

runs:
  using: "composite"
  steps:
    - name: Do something
      run: echo "${{inputs.who-to-greet}} ${{inputs.test-input-1}} ${{inputs.test-input-2}}"
      shell: bash
    - run: |
        print_inputs () {
          inputs='${{ toJSON(inputs) }}'
          keys=$(echo $inputs | jq -r ". | keys[]" )
          echo $keys
          for k in $keys; do
            # export variable $k as key in jq ctx
            value=$(echo $inputs | jq --arg key $k -r '.[$key]')
            echo "$k :  $value"
            echo ${key^^%INPUT}
          done
        }
        print_inputs
      shell: bash
  
