name: Test workflow with dispatch 2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  job3:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Use action is this repo
        uses: ./.github/test-action
        with:
          input-who-to-greet: Tuomas
          input-test-input-1: Jeejee
          input-test-input-2: Joojoo
      
      - name: Docker meta
        id: meta
        with:
          images: name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern=w{{version}}
            type=semver,pattern=w{{major}}.{{minor}}
            type=semver,pattern=w{{major}}.{{minor}}.{{patch}}
            type=semver,pattern=w{{major}}
            type=raw,value=uusintauutta,enable=${{ github.ref == 'refs/heads/man' }}
            type=raw,enable=true,priority=200,prefix=,suffix=,value=yeeha
          flavor: |
            latest=false

        uses: docker/metadata-action@v4
      
      - name: Test docker meta output tags
        run: echo '${{ steps.meta.outputs.tags }}'
      - name: Test docker meta output labels
        run: echo '${{ steps.meta.outputs.labels }}'
      - name: Test docker meta output version
        run: echo '${{ steps.meta.outputs.version }}'
      
