name: Test workflow with dispatch 2

env:
  MY_STUFF: "my stuff"
  NEW_STUFF: "new stuff!"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  job3:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Use action is this repo
        uses: ./.github/test-action
        with:
          input-who-to-greet: Tuomas
          input-test-input-1: Jeejee
          input-test-input-2: Joojoo

      - name: Echo MY_STUFF
        run: echo "My_STUFF -> $MY_STUFF"

      - name: Set empty env
        run: echo "MY_STUFF=$NEW_STUFF" >> $GITHUB_ENV
      
      - name: Echo MY_STUFF again
        run: echo "MY_STUFF -> $MY_STUFF"

      - name: Docker meta
        id: meta
        with:
          images: name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern=w{{version}}
            type=semver,pattern=w{{major}}.{{minor}}
            type=semver,pattern=w{{major}}.{{minor}}.{{patch}}
            type=semver,pattern=w{{major}}
            type=raw,value=uusintauutta,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,enable=true,priority=200,prefix=,suffix=,value=yeeha
            type=raw,value=default-branch,enable={{is_default_branch}}
            type=raw,value=tagitus,enable=${{ startsWith(github.ref, 'refs/tags/') }}
          flavor: |
            latest=false

        uses: docker/metadata-action@v4
      
      - name: Test docker meta output tags
        run: echo '${{ steps.meta.outputs.tags }}'
      - name: Test docker meta output labels
        run: echo '${{ steps.meta.outputs.labels }}'
      - name: Test docker meta output version
        run: echo '${{ steps.meta.outputs.version }}'
      
      - name: Github event name
        run: echo "event name ${{ github.event_name }}"
  
  job4:
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Echo MY_STUFF
        run: echo "My_STUFF -> $MY_STUFF"


  # if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}