name: Test workflow with dispatch

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: |
          echo hello world
          echo "FOOFOO=foofoo" >> GITHUB_ENV
    
      - name: Test custom action in it's own repo
        id: my-action
        uses: pimpbot9000/hello-world-action@main
        with:
          who-to-greet: "Tumppu"
