name: Test workflow with dispatch 2

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job3:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Use action is this repo
        uses: ./.github/test-action
        with:
          input-who-to-greet: Tuomas
          input-test-input-1: Jeejee
          input-test-input-2: Joojoo
      
      - name: Docker meta
        id: meta
        with:
          images: name/app
        uses: docker/metadata-action@v4
      
      - name: Test docker meta outputs
        run: |
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.labels }}
      
